# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: swift-deluxe-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: swift-deluxe-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}
  environment:
    DYNAMODB_TABLE: Menu_Items_SwiftDeluxe

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  getMenuItems:
    handler: functions/userfunctions/getmenu.getMenuItems
    events:
      - httpApi:
          path: /menu-items
          method: get

  createOrder:
    handler: functions/userfunctions/neworder.neworder
    events:
      - httpApi:
          path: /order
          method: post
resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders_SwiftDeluxe
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
