# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: swift-deluxe-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: swift-deluxe-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}
  environment:
    DYNAMODB_TABLE: Menu_Items_SwiftDeluxe
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    cors: true

functions:
  registerUser:
    handler: functions/userfunctions/addnewuser.handler
    events:
      - httpApi:
          path: /register
          method: post

  loginUser:
    handler: functions/userfunctions/loginUser.handler
    events:
      - httpApi:
          path: /login
          method: post

  getMenuItems:
    handler: functions/userfunctions/getmenu.getMenuItems
    events:
      - httpApi:
          path: /menu-items
          method: get

  createOrder:
    handler: functions/userfunctions/neworder.neworder
    events:
      - httpApi:
          path: /order
          method: post

  updateOrder:
    handler: functions/updateorder.updateOrderItemsAndMessage
    events:
      - httpApi:
          path: /order
          method: put

  getorders:
    handler: functions/adminfunctions/getorders.getOrders
    events:
      - httpApi:
          path: /order
          method: get

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders_SwiftDeluxe
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-db
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH # Partition key
        BillingMode: PAY_PER_REQUEST
