# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: swift-deluxe-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: swift-deluxe-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}
  environment:
    JWT_SECRET: ${env:JWT_SECRET}  
  httpApi:
    cors: true  

functions:
  registerUser:
    handler: functions/userfunctions/addnewuser.handler
    events:
      - httpApi:
          path: /register
          method: post

  loginUser:
    handler: functions/userfunctions/loginUser.handler
    events:
      - httpApi:
          path: /login
          method: post
         

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-db
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH  # Huvudnyckel (Partition key)
        BillingMode: PAY_PER_REQUEST
        
